// Declare global variables, shared between the stages
def existingHistoryContent = ""
def firstValueNumber
def operationName
def calculation
def secondValueNumber
def total

pipeline {
    agent any
    parameters {  
        string (name: 'firstValue', description: 'Type the first value.')
        choice (name: 'operation', choices: ['+', '-'], description: 'Choose + for addition or - for subtraction.')
        string (name: 'secondValue', description: 'Type the second value.')
        booleanParam (name: 'showHistory', defaultValue: true, description: 'Select the checkbox to show calculation history')
    } 

    stages {

        stage('Check operation') {
            steps {          
                script {
                                        
                    // Check if the parameter is "+" or "-". Fail the pipeline if it doesn't match any of the values
                    if (params.operation == '+') operationName = 'addition'
                    else if (params.operation == '-') operationName = 'subtraction'
                    else error("The operation chosen is unknown")
                    
                    // Show the operation name on the console
                    echo "The operation chosen is: ${operationName}"
                }
            }
        }

        stage('Call calculation pipeline') {
            steps {
                script {
                    
                    // To build the calculation job passing the values and operation as parameters. The result will be stored on the calculation variable
                    calculation = build job: 'jenkins-calculator-calculate', parameters: [
                        string (name: 'firstValue', value: firstValue),
                        string (name: 'operationName', value: operationName),
                        string (name: 'secondValue', value: secondValue)
                    ]                    
                }
            }
        }

        stage('Show the total') {
            steps {
                script {
                    
                    // To get the total from the calculation job
                    total = calculation.buildVariables.total
                    
                    // Show the total on the console
                    if (operationName == 'addition') echo "${firstValue} + ${secondValue} = ${total}"
                    else if (operationName == 'subtraction')echo "${firstValue} - ${secondValue} = ${total}"
                }
            }
        }      

        stage('Show the calculation history') {
            steps {
                script {
                    if (params.showHistory == true) {
                        existingHistoryContent = readFile '/var/lib/jenkins/workspace/jenkins-calculator-calculate/history.txt'
                        echo "Calculation history:\n${existingHistoryContent}"
                    }
                    else echo "The user chose not to show the calculation history"
                }
            }
        }        
    }
}