// Declare global variables, shared between the stages
def existingHistoryContent = ""
def firstValueNumber
def secondValueNumber

pipeline {
    agent any
    
    parameters {  
        string (name: 'firstValue')
        string (name: 'operationName')
        string (name: 'secondValue')
    }

    environment {
        total
    }

    stages {

        stage('Show received values') {
            steps {          
                script {

                    // Show received values on the console         
                    echo "Received Values"
                    echo "firstValue = ${firstValue}"
                    echo "operationName = ${operationName}"
                    echo "secondValue = ${secondValue}"
                }
            }
        }        
        
        stage('Convert values') {
            steps {          
                script {
                                        
                    // Try to convert the values from string to float. In case of failure, fail the pipeline showing an error message. The values were received as strings because it is not possible to receive them directly as floats. It would be possible to receive them as integers

                    try {
                        firstValueNumber = params.firstValue.toFloat()
                    }
                    catch (NumberFormatException e) {
                        error "Invalid number format: ${params.firstValue}"
                    }

                    try {
                        secondValueNumber = params.secondValue.toFloat()
                    }
                    catch (NumberFormatException e) {
                        error "Invalid number format: ${params.secondValue}"
                    }

                    // Show converted values on the console         
                    echo "Converted Values"
                    echo "firstValueNumber = ${firstValueNumber}"
                    echo "secondValueNumber = ${secondValueNumber}"
                }
            }
        }

        stage('Calculate') {
            steps {
                script {
                    
                    // Execute the operation
                    if (operationName == 'addition') env.total = firstValueNumber + secondValueNumber    
                    else if (operationName == 'subtraction') env.total = firstValueNumber - secondValueNumber

                    // Show the total on the console
                    echo "total = ${env.total}"
                }
            }
        }

        stage('Store on calculations history') {
            steps {
                script {
                    
                    // Declare variables
                    def newHistoryContent

                    // Store the calculation on newHistoryContent variable
                    if (operationName == 'addition') newHistoryContent = "${firstValueNumber} + ${secondValueNumber} = ${env.total}\n"
                    else if (operationName == 'subtraction') newHistoryContent = "${firstValueNumber} - ${secondValueNumber} = ${env.total}\n"

                    // Store the calculation on a history file. Create the file if it does not exist
                    try {
                        existingHistoryContent = readFile 'history.txt'
                    } catch (Exception e) {
                        echo "History file does not exist yet. Creating a new one."
                    }
                    writeFile file: 'history.txt', text: existingHistoryContent + newHistoryContent
                }
            }
        }             
    }
}